### ISSUE TITLE
Tsc errors

### ISSUE THREAD

**Issue by bart-1990** [elliotforbes/ng-diff-match-patch#1]
I followed the installation steps mentioned on this github but when I run the tsc command in my project, I get a bunch of compilation errors (see below).
Is it possible to look into this? The tsc version I'm using is 2.1.5.

node_modules/ng-diff-match-patch/src/diff.directive.ts(20,15): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(62,5): error TS7023: 'diff_main' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(62,16): error TS7006: Parameter 'text1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(62,23): error TS7006: Parameter 'text2' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(62,30): error TS7006: Parameter 'opt_checklines' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(62,47): error TS7006: Parameter 'opt_deadline' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(104,11): error TS7022: 'diffs' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(130,5): error TS7023: 'diff_compute_' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(130,20): error TS7006: Parameter 'text1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(130,27): error TS7006: Parameter 'text2' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(130,34): error TS7006: Parameter 'checklines' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(131,7): error TS7006: Parameter 'deadline' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(175,11): error TS7022: 'diffs_a' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(176,11): error TS7022: 'diffs_b' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(199,5): error TS7023: 'diff_lineMode_' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(199,21): error TS7006: Parameter 'text1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(199,28): error TS7006: Parameter 'text2' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(199,35): error TS7006: Parameter 'deadline' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(206,9): error TS7022: 'diffs' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(268,5): error TS7023: 'diff_bisect_' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(268,19): error TS7006: Parameter 'text1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(268,26): error TS7006: Parameter 'text2' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(268,33): error TS7006: Parameter 'deadline' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(391,5): error TS7023: 'diff_bisectSplit_' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(391,24): error TS7006: Parameter 'text1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(391,31): error TS7006: Parameter 'text2' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(391,38): error TS7006: Parameter 'x' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(391,41): error TS7006: Parameter 'y' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(391,44): error TS7006: Parameter 'deadline' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(398,11): error TS7022: 'diffs' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(399,11): error TS7022: 'diffsb' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(416,25): error TS7006: Parameter 'text1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(416,32): error TS7006: Parameter 'text2' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(438,27): error TS7006: Parameter 'text' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(438,33): error TS7006: Parameter 'lineArray' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(438,44): error TS7006: Parameter 'lineHash' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(474,25): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(474,32): error TS7006: Parameter 'lineArray' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(493,24): error TS7006: Parameter 'text1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(493,31): error TS7006: Parameter 'text2' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(524,24): error TS7006: Parameter 'text1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(524,31): error TS7006: Parameter 'text2' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(558,26): error TS7006: Parameter 'text1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(558,33): error TS7006: Parameter 'text2' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(610,22): error TS7006: Parameter 'text1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(610,29): error TS7006: Parameter 'text2' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(670,20): error TS7006: Parameter 'longtext' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(670,30): error TS7006: Parameter 'shorttext' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(670,41): error TS7006: Parameter 'i' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(670,44): error TS7006: Parameter 'dmp' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(702,27): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(817,35): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(828,41): error TS7006: Parameter 'one' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(828,46): error TS7006: Parameter 'two' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(944,29): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1026,24): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1156,18): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1156,25): error TS7006: Parameter 'loc' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1189,32): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1221,17): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1237,17): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1254,23): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1289,19): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1316,21): error TS7006: Parameter 'text1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1316,28): error TS7006: Parameter 'delta' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1371,17): error TS7006: Parameter 'text' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1371,23): error TS7006: Parameter 'pattern' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1371,32): error TS7006: Parameter 'loc' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1403,19): error TS7006: Parameter 'text' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1403,25): error TS7006: Parameter 'pattern' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1403,34): error TS7006: Parameter 'loc' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1421,32): error TS7006: Parameter 'e' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1421,35): error TS7006: Parameter 'x' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1518,22): error TS7006: Parameter 'pattern' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1537,24): error TS7006: Parameter 'patch' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1537,31): error TS7006: Parameter 'text' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1599,17): error TS7006: Parameter 'a' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1599,20): error TS7006: Parameter 'opt_b' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1599,27): error TS7006: Parameter 'opt_c' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1717,21): error TS7006: Parameter 'patches' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1745,18): error TS7006: Parameter 'patches' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1745,27): error TS7006: Parameter 'text' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1851,23): error TS7006: Parameter 'patches' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(1910,31): error TS7006: Parameter 'patches' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(2002,19): error TS7006: Parameter 'patches' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(2017,21): error TS7006: Parameter 'textline' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(2018,9): error TS7034: Variable 'patches' implicitly has type 'any[]' in some locations where its type cannot be determined.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(2020,14): error TS7005: Variable 'patches' implicitly has an 'any[]' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(2098,3): error TS7008: Member 'diffs' implicitly has an 'any[]' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(2099,3): error TS7008: Member 'start1' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/diffMatchPatch.ts(2100,3): error TS7008: Member 'start2' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/lineDiff.directive.ts(19,15): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/processingDiff.directive.ts(18,15): error TS7006: Parameter 'diffs' implicitly has an 'any' type.
node_modules/ng-diff-match-patch/src/semanticDiff.directive.ts(18,15): error TS7006: Parameter 'diffs' implicitly has an 'any' type.

**Comment by elliotforbes** [comment]
Sorry to hear! I'll have to have a look at it next week unfortunately!

**Comment by deroude** [comment]
You can do the TSC compilation with the "noImplicitAny":false flag (https://angular.io/docs/ts/latest/guide/typescript-configuration.html)

**Comment by elliotforbes** [comment]
This has been solved by @rars pull request.
