### ISSUE TITLE
Error: (SystemJS) XHR error (404 Not Found)

### ISSUE THREAD

**Issue by pavan-laddu2000** [elliotforbes/ng-diff-match-patch#22]
Getting below after following the Usage steps.

Error loading http://localhost:3000/ng-diff-match-patch as "ng-diff-match-patch" from http://localhost:3000/app/app.module.js

I am using Angular 4, any suggestion would be appreciated.

Sorry to ask if it is a basic/silly question, as I am new to this JS world.

**Comment by pavan-laddu2000** [comment]
@elliotforbes any suggestions, I am struck at here. Can you please help me.

**Comment by elliotforbes** [comment]
Hi, without seeing your code I am unfortunately unable to help, however from a quick glance it looks like you are trying to hit ng-diff-match-patch as a route, it's ideally meant to be used as a directive within a page in your application.

I will try to write a more comprehensive tutorial and post it once I get a spare bit of time!

**Comment by elliotforbes** [comment]
Closing as I believe this is fixed in version 3.0.1
