### ISSUE TITLE
index.ts is not part of the compilation output.

### ISSUE THREAD

**Issue by Pikachews** [elliotforbes/ng-diff-match-patch#24]
This issue seems to come up when using Angular v5.0.0.
It's being discussed here: https://github.com/angular/angular-cli/issues/8263
A workaround to this issue can be found here: https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325
But is it possible to get it fixed in the package itself?

Long story short: TS source files shouldn't be included in the package.
A simple, temporary fix for users of this package is to simply rename `index.ts` to `index.js`.

**Comment by flaska** [comment]
+1 Same for me after upgrading to sweet A5.

**Comment by moose4lord** [comment]
I fell victim to this issue too. The suggestion to rename index.ts to index,js worked for me. Thanks for the tip. Be nice to get the package fixed. I know I'm going to delete my node_module directory someday and do a "npm install" and be right back here. :)

**Comment by dae721** [comment]
Here's an alternative workaround that worked for me. Instead of renaming index.ts, I added the following to tsconfig.json:
```
  "include": [
    "node_modules/ng-diff-match-patch/index.ts",
    "src/**/*"
  ]
```

**Comment by oudekaas** [comment]
Same issue here, dae721 comment works for me, so added it to the tsconfig.json file.

ERROR in ./node_modules/ngx-markdown-editor/index.ts
Module build failed: Error: D:\chat\mean-chat\node_modules\ngx-markdown-editor\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (D:\chat\mean-chat\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:648:23)
    at plugin.done.then (D:\chat\mean-chat\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 54:0-60
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by randyaa** [comment]
I added the following as a node script that now runs before any of my builds:

```
var fs = require('fs');
(function() {
    fs.exists( './node_modules/ng-diff-match-patch/index.ts', (exists) => {
        if (exists) {
            fs.renameSync('./node_modules/ng-diff-match-patch/index.ts', './node_modules/ng-diff-match-patch/index.js');
            console.log('Renamed ng-diff-match-patch/index.ts to .js');
        } else {
            //TODO this script is only needed until there's a resolution to https://github.com/elliotforbes/ng-diff-match-patch/issues/24
            console.log('No ng-diff-match-patch/index.ts to rename! CAN THE SCRIPT BE REMOVED NOW?')
        }
    });
})();
```

not the best solution but it takes care of it for now. I'm not sure why but @dae721 's solution didn't work for me but i didn't spend time investigating why.

**Comment by elliotforbes** [comment]
Hi @bjarecki,
can you try again with the 3.0.1 version now published on NPM?
Kind Regards,
Elliot

**Comment by moose4lord** [comment]
I tried v3.0.1 in my Angular 5 dev env and this issue seems to be fixed now. No more "index.ts is missing from the TypeScript compilation" error. It also works with Angular 6. Nice job, Elliot. Thanks.

**Comment by elliotforbes** [comment]
@AndersTornkvist  thank you very much for providing the fix for this issue! You are an absolute legend.
