### ISSUE TITLE
Issue with Angular Rollup

### ISSUE THREAD

**Issue by lexon0011** [elliotforbes/ng-diff-match-patch#25]
Hello,

we use your library in our Angular 4 project as descripted in your documention. But we have issues in the angular rollup process. I try to add the follwing to our rollup config: 

```
plugins: [
   commonjs({
      namedExports: {
         "node_modules/ng-diff-match-patch/dist/diffMatchPatch.bundle.js": ["DiffMatchPatchModule"]
      },
      include: [
         "node_modules/**"
      ]
   })
]
```

In the rollup process I get the following message:
```
'ng-diff-match-patch' is imported by dist\tmp\src\app\modules\shared\shared.module.js, but could not be resolved – treating it as an external dependency
No name was provided for external module 'ng-diff-match-patch' in options.globals – guessing 'ngDiffMatchPatch
```

At runtime I get the following error in the developer console:
`Uncaught ReferenceError: ngDiffMatchPatch is not defined`

Whats the correct way to use your library with angular Aot/Rollup?

Thanks!

**Comment by elliotforbes** [comment]
I believe this should have been addressed in version 3.0.1, can you reopen the issue if the problem persists?
